### ISSUE TITLE
Data Application

### ISSUE THREAD

**Issue by jerryniu0624** [YoungP2001/DBSR#2]
Can you provide the input data for training and testing? Or the python script for reproducing those inputs from the original HSI datasets? Thanks a lot!

**Comment by jerryniu0624** [comment]
![image](https://github.com/user-attachments/assets/97d25349-266a-43c9-a0e9-823cc881b8d7)

**Comment by jerryniu0624** [comment]
I have seen the production script.
![image](https://github.com/user-attachments/assets/05a9eb7f-f29d-4d2c-8c15-a589df48a139)

Can you provide the data in sourcedir = "/home/lwd/Dataset_yp/HSISR/Chikusei/8/Chikusei_x8/trains_large/"? My downloaded Chikusei file is not separated into Train and Val daatset
![image](https://github.com/user-attachments/assets/1375c7f9-8221-4eb5-9d17-782bcac4037e)

**Comment by YoungP2001** [comment]
I can send the Matlab scripts to you by email.

**Comment by jerryniu0624** [comment]
Appreciate it!!

**Comment by YoungP2001** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YoungP2001/DBSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月9日(星期一) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YoungP2001/DBSR] Data Application (Issue #2)





 
Appreciate it!!

**Comment by sikongconglu** [comment]
您好，我也需要处理好的数据集，可以发我邮箱吗？3415261914@qq.com
