### ISSUE TITLE
"CLS" is not defined

### ISSUE THREAD

**Issue by jerryniu0624** [YoungP2001/DBSR#3]
![image](https://github.com/user-attachments/assets/853b0a08-92c1-4a29-b305-db83183d050f)
Where is the CLS

**Comment by YoungP2001** [comment]
Sorry, CLS should be changed to DWDN.

**Comment by jerryniu0624** [comment]
Thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YoungP2001/DBSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月9日(星期一) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YoungP2001/DBSR] "CLS" is not defined (Issue #3)





 
Sorry, CLS should be changed to DWDN.
